if [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi

SESSION_TYPE=""
if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
    SESSION_TYPE=remote/ssh
else
    case $(ps -o comm= -p $PPID) in
        sshd|*/sshd) SESSION_TYPE=remote/ssh;;
    esac
fi

if [[ $SESSION_TYPE = 'remote/ssh' ]]; then
    export PROMPT_GIT_COLOR=$PROMPT_COLOR
    export PROMPT_COLOR=$C_BLUE #"38;5;69"
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '~/google-cloud-sdk/path.bash.inc' ]; then . '~/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '~/google-cloud-sdk/completion.bash.inc' ]; then . '~/google-cloud-sdk/completion.bash.inc'; fi
